export const ACTION_TYPE = {
	SET_USER: "SET_USER",
	LOGOUT: "LOGOUT",
	SET_PROJECT_DATA: "SET_PROJECT_DATA",
	RESET_PROJECT_DATA: "RESET_PROJECT_DATA",
	SET_TASK_DATA: "SET_TASK_DATA",
	SET_TASKS: "SET_TASKS",
	RESET_TASK_DATA: "RESET_TASK_DATA",
};
